baseURL = "https://asadowski.com"
locale = "en-us"
title = "albert's notes"

[params]
    description = "Notes and publications by Albert Sadowski - software engineer interested in security and machine learning."
    copyright = "Copyright © 2026 Albert Sadowski"
    highlight = true
    mainSections = ["posts"]

    [[params.contact]]
        name = "GitHub"
        url = "https://github.com/albsadowski"

    [[params.contact]]
        name = "LinkedIn"
        url = "https://www.linkedin.com/in/albertsadowski"

    [[params.contact]]
        name = "Google Scholar"
        url = "https://scholar.google.com/citations?user=kDoZLE0AAAAJ"

[markup]
    [markup.highlight]
        noClasses = false
        style = "github"

[permalinks]
    posts = "/:title/"
